#!/usr/bin/env node

const { DoughnutResearchAgent } = require("./research-agent");
const fs = require("fs");
const path = require("path");

const USAGE = `
Doughnut Economics Research Agent
=================================
AI-powered tool to populate city portrait data with sourced indicators.

Usage:
  node cli.js <city> <state> [options]

Examples:
  node cli.js "Santa Cruz" "California"
  node cli.js "Portland" "Oregon" --ring social
  node cli.js "Amsterdam" "Netherlands" --dimensions "housing,food,health"
  node cli.js "Santa Cruz" "California" --output portrait.json

Options:
  --ring <social|ecological|both>   Which ring to research (default: both)
  --dimensions <dim1,dim2,...>      Specific dimensions to research
  --output <file>                   Output file path (default: stdout)
  --format <json|datajs>            Output format (default: json)
  --population <pop>                Population string (e.g., "~65,000")
  --description <desc>              City description
  --parallel <n>                    Max concurrent API requests (default: 3)
  --verbose                         Show progress messages
  --model <model>                   LLM model to use (default: gpt-4o)
  --base-url <url>                  API base URL (for non-OpenAI providers)
  --api-key <key>                   API key (or set LLM_API_KEY env var)

Environment Variables:
  LLM_API_KEY      API key (works with any OpenAI-compatible provider)
  LLM_BASE_URL     API base URL
  LLM_MODEL        Model name
  OPENAI_API_KEY   OpenAI API key (fallback)
  OPENAI_BASE_URL  OpenAI base URL (fallback)

Provider Examples:
  # OpenAI
  LLM_API_KEY=sk-... node cli.js "Portland" "Oregon"

  # Anthropic (via openai-compatible proxy like litellm)
  LLM_BASE_URL=http://localhost:4000/v1 LLM_MODEL=claude-sonnet-4-20250514 node cli.js "Portland" "Oregon"

  # Ollama (local)
  LLM_BASE_URL=http://localhost:11434/v1 LLM_MODEL=llama3 LLM_API_KEY=ollama node cli.js "Portland" "Oregon"

  # Any OpenAI-compatible API
  LLM_BASE_URL=https://your-provider.com/v1 LLM_API_KEY=... node cli.js "Portland" "Oregon"
`;

function parseArgs(argv) {
    const args = { _: [] };
    for (let i = 2; i < argv.length; i++) {
        const arg = argv[i];
        if (arg === "--help" || arg === "-h") {
            console.log(USAGE);
            process.exit(0);
        } else if (arg.startsWith("--")) {
            const key = arg.slice(2);
            const val = argv[++i];
            args[key] = val;
        } else {
            args._.push(arg);
        }
    }
    return args;
}

function toDataJS(portrait, varName) {
    const key = portrait.name.toLowerCase().replace(/[^a-z0-9]+/g, "_");
    return `// Generated by doughnut-research-agent
// Run: node cli.js "${portrait.name}" --format datajs
// Date: ${new Date().toISOString().split("T")[0]}
// Model: ${process.env.LLM_MODEL || "gpt-4o"}

const JURISDICTIONS = {
    "${key}": ${JSON.stringify(portrait, null, 4)}
};
`;
}

async function main() {
    const args = parseArgs(process.argv);

    if (args._.length < 2) {
        console.error("Error: city and state are required.\n");
        console.log(USAGE);
        process.exit(1);
    }

    const [city, state] = args._;

    // Check for API key
    const apiKey = args["api-key"] || process.env.LLM_API_KEY || process.env.OPENAI_API_KEY;
    if (!apiKey) {
        console.error("Error: No API key found.");
        console.error("Set LLM_API_KEY or OPENAI_API_KEY environment variable, or pass --api-key.\n");
        process.exit(1);
    }

    const agent = new DoughnutResearchAgent({
        apiKey,
        baseURL: args["base-url"] || process.env.LLM_BASE_URL || process.env.OPENAI_BASE_URL,
        model: args.model || process.env.LLM_MODEL,
        verbose: "verbose" in args
    });

    const options = {};
    if (args.ring) options.ring = args.ring;
    if (args.dimensions) options.dimensions = args.dimensions.split(",").map(d => d.trim());
    if (args.parallel) options.parallel = parseInt(args.parallel);

    console.error(`Researching ${city}, ${state}...`);
    console.error(`Model: ${args.model || process.env.LLM_MODEL || "gpt-4o"}`);
    console.error(`Ring: ${args.ring || "both"}`);
    if (args.dimensions) console.error(`Dimensions: ${args.dimensions}`);
    console.error("");

    const portrait = await agent.buildPortrait(
        city,
        state,
        args.population,
        args.description
    );

    const format = args.format || "json";
    let output;

    if (format === "datajs") {
        output = toDataJS(portrait);
    } else {
        output = JSON.stringify(portrait, null, 2);
    }

    if (args.output) {
        const outPath = path.resolve(args.output);
        fs.writeFileSync(outPath, output);
        console.error(`\nWritten to ${outPath}`);
    } else {
        console.log(output);
    }

    // Print summary
    const eco = portrait.ecological || [];
    const soc = portrait.social || [];
    const highConf = [...eco, ...soc].filter(d => d.confidence === "high").length;
    const medConf = [...eco, ...soc].filter(d => d.confidence === "medium").length;
    const lowConf = [...eco, ...soc].filter(d => d.confidence === "low").length;

    console.error(`\nResearch complete for ${city}, ${state}`);
    console.error(`  Ecological: ${eco.length} dimensions`);
    console.error(`  Social:     ${soc.length} dimensions`);
    console.error(`  Confidence: ${highConf} high, ${medConf} medium, ${lowConf} low`);
}

main().catch(err => {
    console.error("Error:", err.message);
    process.exit(1);
});
